"""Values students may change while completing Lab 3."""

import numpy as np

# Task definition -----------------------------------------------------------------
# The supplied target pose is generated by the goal keyframe in the MuJoCo model.
# Position is in meters; rotation is a 3x3 rotation matrix.
START_Q = np.deg2rad([-90.0, -90.0, -90.0, -90.0, 90.0, 0.0])
GOAL_POSITION = np.array([0.10915, 0.48690, 0.432159])
GOAL_ROTATION = np.diag([1.0, -1.0, -1.0])
IK_SEED = np.deg2rad([85.0, -85.0, -95.0, -85.0, 85.0, 5.0])

# Collision and planning -----------------------------------------------------------
SAFETY_MARGIN = 0.0  # meters; values up to 0.03 are supported by this scene
PATH_VALIDATION_DISTANCE = 0.02  # maximum joint change between checks, radians
PLANNER_VALIDATION_DISTANCE = 0.04  # OMPL state-check spacing, radians
MAX_CONNECTION_DISTANCE = 0.35  # maximum RRT extension, radians
PLANNING_TIMEOUT = 3.0  # seconds
PLANNER_SEED = 4

# Task 2 parameter experiment. Keep this small enough to run interactively.
CONNECTION_DISTANCE_EXPERIMENT = (0.15, 0.35, 0.70)
EXPERIMENT_TRIALS = 3

# Trajectory generation ------------------------------------------------------------
TRAJECTORY_DT = 0.02  # seconds
JOINT_SPEED_LIMITS = np.full(6, 0.60)  # radians/second
BLEND_TIME = 0.20  # seconds for mstraj polynomial blends

# Browser viewer -------------------------------------------------------------------
VIEWER_PORT = 8080
